### ISSUE TITLE
Issue when installing a node in node red 

### ISSUE THREAD

**Issue by rafaelsousa** [open-rpa/docker#1]
When installing the following node in the pallete :

![image](https://user-images.githubusercontent.com/53796/220975398-30020800-bc4f-4791-9c54-eb43e6f66fb9.png)

I've got this error message and here's the log for this error :

`2023-02-23T15:43:01.767Z Install : @martip/node-red-pdf-to-png 1.0.1

2023-02-23T15:43:01.771Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict @martip/node-red-pdf-to-png@1.0.1
2023-02-23T15:43:02.016Z [err] npm
2023-02-23T15:43:02.017Z [err]  WARN config
2023-02-23T15:43:02.017Z [err]  production Use `--omit=dev` instead.
2023-02-23T15:43:06.272Z [err] npm ERR!
2023-02-23T15:43:06.272Z [err]  code 1
2023-02-23T15:43:06.272Z [err] npm ERR! path /data/.nodered-rafaelaiteraca/node_modules/canvas
2023-02-23T15:43:06.273Z [err] npm ERR!
2023-02-23T15:43:06.273Z [err]  command failed
2023-02-23T15:43:06.273Z [err] npm 
2023-02-23T15:43:06.273Z [err] ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary
2023-02-23T15:43:06.273Z [err] npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/data/.nodered-rafaelaiteraca/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/data/.nodered-rafaelaiteraca/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
2023-02-23T15:43:06.273Z [err] npm ERR! node-pre-gyp info it worked if it ends with ok
2023-02-23T15:43:06.273Z [err] npm 
2023-02-23T15:43:06.273Z [err] ERR! node-pre-gyp info using node-pre-gyp@1.0.10
2023-02-23T15:43:06.273Z [err] npm ERR! node-pre-gyp info using node@18.13.0 | linux | x64
2023-02-23T15:43:06.273Z [err] npm ERR!
2023-02-23T15:43:06.273Z [err]  node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.0/canvas-v2.11.0-node-v108-linux-musl-x64.tar.gz
2023-02-23T15:43:06.273Z [err] npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.0/canvas-v2.11.0-node-v108-linux-musl-x64.tar.gz 
2023-02-23T15:43:06.273Z [err] npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.0 and node@18.13.0 (node-v108 ABI, musl) (falling back to source compile with node-gyp) 
2023-02-23T15:43:06.273Z [err] npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.0/canvas-v2.11.0-node-v108-linux-musl-x64.tar.gz 
2023-02-23T15:43:06.273Z [err] npm ERR! gyp info it worked if it ends with ok
2023-02-23T15:43:06.273Z [err] npm
2023-02-23T15:43:06.273Z [err]  ERR! gyp info using node-gyp@9.3.1
2023-02-23T15:43:06.273Z [err] npm ERR! gyp info using node@18.13.0 | linux | x64
2023-02-23T15:43:06.273Z [err] npm ERR! gyp info ok 
2023-02-23T15:43:06.273Z [err] npm ERR! gyp info it worked if it ends with ok
2023-02-23T15:43:06.273Z [err] npm ERR! gyp info using node-gyp@9.3.1
2023-02-23T15:43:06.273Z [err] npm ERR!
2023-02-23T15:43:06.273Z [err]  gyp info using node@18.13.0 | linux | x64
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! find Python 
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
2023-02-23T15:43:06.273Z [err] npm
2023-02-23T15:43:06.273Z [err]  ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! find Python checking if "python3" can be used
2023-02-23T15:43:06.273Z [err] npm ERR!
2023-02-23T15:43:06.273Z [err]  gyp ERR! find Python - "python3" is not in PATH or produced an error
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! find Python checking if "python" can be used
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! find Python 
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! find Python **********************************************************
2023-02-23T15:43:06.273Z [err] npm ERR!
2023-02-23T15:43:06.273Z [err]  gyp ERR! find Python You need to install the latest version of Python.
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2023-02-23T15:43:06.273Z [err] npm ERR!
2023-02-23T15:43:06.273Z [err]  gyp ERR! find Python you can try one of the following options:
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2023-02-23T15:43:06.273Z [err] npm 
2023-02-23T15:43:06.273Z [err] ERR! gyp ERR! find Python - Set the environment variable PYTHON
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! find Python For more information consult the documentation at:
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2023-02-23T15:43:06.273Z [err] npm ERR!
2023-02-23T15:43:06.273Z [err]  gyp ERR! find Python **********************************************************
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! find Python 
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! configure error 
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/find-python.js:330:47)
2023-02-23T15:43:06.273Z [err] npm 
2023-02-23T15:43:06.273Z [err] ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/find-python.js:159:21)
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/find-python.js:202:16)
2023-02-23T15:43:06.273Z [err] npm ERR!
2023-02-23T15:43:06.273Z [err]  gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/find-python.js:294:16)
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! stack     at exithandler (node:child_process:427:5)
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
2023-02-23T15:43:06.273Z [err] npm ERR!
2023-02-23T15:43:06.273Z [err]  gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! System Linux 5.19.0-32-generic
2023-02-23T15:43:06.273Z [err] npm
2023-02-23T15:43:06.273Z [err]  ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/data/.nodered-rafaelaiteraca/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/data/.nodered-rafaelaiteraca/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! cwd /data/.nodered-rafaelaiteraca/node_modules/canvas
2023-02-23T15:43:06.273Z [err] npm ERR!
2023-02-23T15:43:06.273Z [err]  gyp ERR! node -v v18.13.0
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! node-gyp -v v9.3.1
2023-02-23T15:43:06.273Z [err] npm ERR! gyp ERR! not ok 
2023-02-23T15:43:06.273Z [err] npm ERR! node-pre-gyp ERR! build error 
2023-02-23T15:43:06.273Z [err] npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/data/.nodered-rafaelaiteraca/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/data/.nodered-rafaelaiteraca/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
2023-02-23T15:43:06.273Z [err] npm 
2023-02-23T15:43:06.273Z [err] ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/data/.nodered-rafaelaiteraca/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
2023-02-23T15:43:06.273Z [err] npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
2023-02-23T15:43:06.273Z [err] npm ERR!
2023-02-23T15:43:06.273Z [err]  node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
2023-02-23T15:43:06.273Z [err] npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
2023-02-23T15:43:06.273Z [err] npm ERR! node-pre-gyp ERR! System Linux 5.19.0-32-generic
2023-02-23T15:43:06.273Z [err] npm
2023-02-23T15:43:06.273Z [err]  ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/data/.nodered-rafaelaiteraca/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
2023-02-23T15:43:06.273Z [err] npm ERR! node-pre-gyp ERR! cwd /data/.nodered-rafaelaiteraca/node_modules/canvas
2023-02-23T15:43:06.273Z [err] npm ERR!
2023-02-23T15:43:06.273Z [err]  node-pre-gyp ERR! node -v v18.13.0
2023-02-23T15:43:06.273Z [err] npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
2023-02-23T15:43:06.273Z [err] npm ERR! node-pre-gyp ERR! not ok
2023-02-23T15:43:06.274Z [err] 
2023-02-23T15:43:06.274Z [err] npm ERR!
2023-02-23T15:43:06.274Z [err]  A complete log of this run can be found in:
2023-02-23T15:43:06.274Z [err] npm ERR!     /root/.npm/_logs/2023-02-23T15_43_02_005Z-debug-0.log
2023-02-23T15:43:06.287Z rc=1
`

As far as I understand, it misses python3 at the node-red image ? What could we possible do to fix this ?

Thank you!

**Comment by skadefro** [comment]
please use https://discourse.openiap.io/ for issues that is not directly related to the docker files.
( and in this case, this is an issue with module and not nodered. You are trying to install a module on a docker image that does not contain build tools. I don't offer images that allow that, you need to create them your self )

**Comment by skadefro** [comment]
closing this for now. Feel free to reach out on discourse if this is still an issue
